Running stage '07_SN10_openset_NDBK':
> python scripts/script_07_SN10_openset_NDBK.py
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/eugen/miniconda3/envs/nco/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/eugen/miniconda3/envs/nco/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "scripts/script_07_SN10_openset_NDBK.py", line 74, in multiprocessing_wrapper_script_07
    run_main_06(
  File "/data/sources/eugen/negative-class-optimization/scripts/script_06_SN10_openset_NDB1.py", line 117, in run_main_06
    train_loader, test_loader, open_loader = construct_loaders_06(
  File "/data/sources/eugen/negative-class-optimization/scripts/script_06_SN10_openset_NDB1.py", line 225, in construct_loaders_06
    farmhash.hash64(df_train_val["Slide"]) % 64
TypeError: argument 1 must be str, not Series
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/script_07_SN10_openset_NDBK.py", line 113, in <module>
    pool.map(multiprocessing_wrapper_script_07, ag_pairs)
  File "/home/eugen/miniconda3/envs/nco/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/eugen/miniconda3/envs/nco/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: argument 1 must be str, not Series
ERROR: failed to reproduce '07_SN10_openset_NDBK': failed to run: python scripts/script_07_SN10_openset_NDBK.py, exited with 1
